Repository pralinkhaira/Project-Wizard, pull requests merged in 2023-10, with the labels that each got.

#4 Added update to ASCII_Art Project
  Projects/Python/ASCII_Art/README.md
  Projects/Python/ASCII_Art/convert_image.py
  Projects/Python/ASCII_Art/templates/index.html
Labels: hacktoberfest-accepted

#7 Added Some of LeetCode's Solutions
  Leet Code Solutions/06. Zigzag Conversion/PralinKhaira-zigzag_conversion.py
  Leet Code Solutions/121. Best Time To Buy And Sell Stock/PralinKhaira-BestTimeToBuyAndSellStock.java
  Leet Code Solutions/125. Valid Palindrome/PralinKhaira-ValidPalindrome.java
  Leet Code Solutions/32. Longest Valid Parentheses/PralinKhaira-LongestValidParentheses.java
  Leet Code Solutions/37. Sudoku Solver/PralinKhaira-Sudoko Solver.java
Labels: hacktoberfest-accepted

#12 Created New solution for problem : Next Smallest Palindrome
  Geeks For Geeks Solutions/Next Smallest Palindrome/Akshant Saini-Next Smallest Palindrome.cpp
Labels: good first issue

#13 Created New solution for problem : Alien Dictionary
  Geeks For Geeks Solutions/Alien Dictionary/Akshant Saini-Alien Dictionary.cpp
Labels: hacktoberfest-accepted

#11 Created New solution for problem : Solve the Sudoku
  Geeks For Geeks Solutions/Solve the Sudoku/Akshant Saini-Solve the Sudoku.cpp
Labels: hacktoberfest-accepted

#15 Push 2
  Projects/Python/Expense_tracker/main.py
Labels: hacktoberfest-accepted

#20 Cyptographer added
  Projects/Python/Cryptographer/Cryptographer.py
  Projects/Python/Cryptographer/decrypted.txt
  Projects/Python/Cryptographer/encrypted.txt
  Projects/Python/Cryptographer/test.txt
Labels: Best-PR, hacktoberfest-accepted
